// Copyright (c) Athena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),
		ACMD_DEF(reloadachievements),
		ACMD_DEF(achievements),
		ACMD_DEF(achieve),
		ACMD_DEF(unachieve),
		ACMD_DEF(mobevent),
		ACMD_DEF(security),
		ACMD_DEF(expinfo),
		ACMD_DEF(mission),
		ACMD_DEF2("costumeitem",item),
		ACMD_DEF(flooritem),
		ACMD_DEF(order),
		ACMD_DEF(leader),
		ACMD_DEF(reportafk),
		ACMD_DEF(adopt),