// Copyright (c) Athena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
	BUILDIN_DEF(achieve,"i"),
	BUILDIN_DEF(achievement_info,"ii"),
	BUILDIN_DEF2(mobevent,"mobevent","siisiiiiiiiiiiiiii?"),
	BUILDIN_DEF(getmobrandid,"ii"),
	BUILDIN_DEF(setsecurity,"i"),
	BUILDIN_DEF(getsecurity,""),
	BUILDIN_DEF(mission_sethunting,"iii"),
	BUILDIN_DEF(mission_settime,"i"),
	BUILDIN_DEF(costume,"i"),
	BUILDIN_DEF(flooritem,"ii"),
	BUILDIN_DEF(playertalk,"is"), // [Karmic]
	BUILDIN_DEF(madoheal,"ii"),
	BUILDIN_DEF(adopt,"vv"),
	BUILDIN_DEF(navigateto,"s???????"),
	BUILDIN_DEF(unitexists,"i"),